### ISSUE TITLE
Bug reproduction in `Branch` can be omitted

### ISSUE THREAD

**Issue by Melirius** [microsoft/lepton_jpeg_rust#49]
Analysing the code I got to conclusion that corner case even if present in the initial code of Lepton, does not affect its behaviour. Citing https://github.com/microsoft/lepton_jpeg_rust/blob/main/src/structs/branch.rs
```
The only corner case is that in the case of 255 true and 1
 false, the C++ version decides to set the probability to 0 for the next
 true value, which is different than the formula ((a << 8) / ( a + b )).
````

The formula produces 1 here, and this does not affect neither https://github.com/microsoft/lepton_jpeg_rust/blob/main/src/structs/vpx_bool_reader.rs#L147 nor https://github.com/microsoft/lepton_jpeg_rust/blob/main/src/structs/vpx_bool_writer.rs#L159 as from [VP8 spec](https://datatracker.ietf.org/doc/html/rfc6386#section-7.2) range of `tmp_range` is [128,255], so that both bugged and formula version give `split = 1`.

**Comment by mcroomp** [comment]
That's pretty cool... thanks! The loop is pretty critical in terms of perf
