### ISSUE TITLE
Idea: prepare predictions for edge DCT coefficients during decoding of previous blocks and of current 7x7 block

### ISSUE THREAD

**Issue by Melirius** [microsoft/lepton_jpeg_rust#70]
As for DC coef prediction, predictors for edge DCT coefficients can also be calculated during block IDCT (they are partial IDCT anyway), and stored inside `NeighborSummary` like `edge_pixels_v/_h`. These predictors are sums of dot products of dequantized coefs from above/left block with the same dot products from current block - dot products can be calculated for current block and used further in decoding of blocks below/to the right.

**Comment by mcroomp** [comment]
Cool idea... as long as all the rounding etc is identical so the format doesn't break

**Comment by Melirius** [comment]
It works, but no performance improvement yet - I'll vectorize and see what happens.

**Comment by mcroomp** [comment]
Got the changes merged, so you can share your branch if you want

**Comment by Melirius** [comment]
It is here https://github.com/Melirius/lepton_jpeg_rust/tree/fasterjpeg_simd_variation, but I had not enough time to polish it and get it faster

**Comment by mcroomp** [comment]
If you get a chance to merge with main... It's a hard to tell what changes are relevant. I tried it but it was a bit of a mess. Thanks!
