### ISSUE TITLE
Logic simplification in `lepton_encode_row_range/decode_row_wrapper`

### ISSUE THREAD

**Issue by Melirius** [microsoft/lepton_jpeg_rust#81]
As `mid_right` is indistinguishable from `middle` and `width_one` from `mid_left`, logic inside these functions can be simplified, as well as lower in `process_row` and `decode_row`.

**Comment by mcroomp** [comment]
I think its vestiges of using the upper right block which never got implemented as far as I can tell, but yeah it can be dramatically simplified. Even one_width isn't necessary. 

I had this change that I was working on #82

**Comment by Melirius** [comment]
Closed by #82
